language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
before_install:
  - sudo ci/travis_setup.sh
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
