name: CI using carnix

on:
  pull_request:
  push:

jobs:
  vm-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: cachix/install-nix-action@v7
      - uses: cachix/cachix-action@v5
        with:
          name: 573-ci
          signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        env:
          NIX_PATH: nixpkgs=channel:nixos-19.09

